// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/online/console/data/protobuf/proto/Auth.proto

package com.online.console.data.protobuf.java;

public final class AuthProtos {
  private AuthProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.online.console.data.protobuf.proto.AuthRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户 token
     * </pre>
     *
     * <code>required string token = 1;</code>
     */
    boolean hasToken();
    /**
     * <pre>
     * 用户 token
     * </pre>
     *
     * <code>required string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <pre>
     * 用户 token
     * </pre>
     *
     * <code>required string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <pre>
     * 用户唯一识别码
     * </pre>
     *
     * <code>required int32 uin = 2;</code>
     */
    boolean hasUin();
    /**
     * <pre>
     * 用户唯一识别码
     * </pre>
     *
     * <code>required int32 uin = 2;</code>
     */
    int getUin();

    /**
     * <pre>
     * 发包时间戳
     * </pre>
     *
     * <code>required int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     * 发包时间戳
     * </pre>
     *
     * <code>required int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * <pre>
   * 认证 Auth
   * </pre>
   *
   * Protobuf type {@code com.online.console.data.protobuf.proto.AuthRequest}
   */
  public  static final class AuthRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.online.console.data.protobuf.proto.AuthRequest)
      AuthRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthRequest.newBuilder() to construct.
    private AuthRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthRequest() {
      token_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              token_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              uin_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.online.console.data.protobuf.java.AuthProtos.AuthRequest.class, com.online.console.data.protobuf.java.AuthProtos.AuthRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <pre>
     * 用户 token
     * </pre>
     *
     * <code>required string token = 1;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 用户 token
     * </pre>
     *
     * <code>required string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 用户 token
     * </pre>
     *
     * <code>required string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UIN_FIELD_NUMBER = 2;
    private int uin_;
    /**
     * <pre>
     * 用户唯一识别码
     * </pre>
     *
     * <code>required int32 uin = 2;</code>
     */
    public boolean hasUin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 用户唯一识别码
     * </pre>
     *
     * <code>required int32 uin = 2;</code>
     */
    public int getUin() {
      return uin_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <pre>
     * 发包时间戳
     * </pre>
     *
     * <code>required int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 发包时间戳
     * </pre>
     *
     * <code>required int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, uin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, uin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.online.console.data.protobuf.java.AuthProtos.AuthRequest)) {
        return super.equals(obj);
      }
      com.online.console.data.protobuf.java.AuthProtos.AuthRequest other = (com.online.console.data.protobuf.java.AuthProtos.AuthRequest) obj;

      boolean result = true;
      result = result && (hasToken() == other.hasToken());
      if (hasToken()) {
        result = result && getToken()
            .equals(other.getToken());
      }
      result = result && (hasUin() == other.hasUin());
      if (hasUin()) {
        result = result && (getUin()
            == other.getUin());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      if (hasUin()) {
        hash = (37 * hash) + UIN_FIELD_NUMBER;
        hash = (53 * hash) + getUin();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.online.console.data.protobuf.java.AuthProtos.AuthRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 认证 Auth
     * </pre>
     *
     * Protobuf type {@code com.online.console.data.protobuf.proto.AuthRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.online.console.data.protobuf.proto.AuthRequest)
        com.online.console.data.protobuf.java.AuthProtos.AuthRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.online.console.data.protobuf.java.AuthProtos.AuthRequest.class, com.online.console.data.protobuf.java.AuthProtos.AuthRequest.Builder.class);
      }

      // Construct using com.online.console.data.protobuf.java.AuthProtos.AuthRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        token_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        uin_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthRequest_descriptor;
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.AuthProtos.AuthRequest getDefaultInstanceForType() {
        return com.online.console.data.protobuf.java.AuthProtos.AuthRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.AuthProtos.AuthRequest build() {
        com.online.console.data.protobuf.java.AuthProtos.AuthRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.AuthProtos.AuthRequest buildPartial() {
        com.online.console.data.protobuf.java.AuthProtos.AuthRequest result = new com.online.console.data.protobuf.java.AuthProtos.AuthRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.token_ = token_;
          to_bitField0_ |= 0x00000001;
        } else {
          result.token_ = "";
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.uin_ = uin_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.online.console.data.protobuf.java.AuthProtos.AuthRequest) {
          return mergeFrom((com.online.console.data.protobuf.java.AuthProtos.AuthRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.online.console.data.protobuf.java.AuthProtos.AuthRequest other) {
        if (other == com.online.console.data.protobuf.java.AuthProtos.AuthRequest.getDefaultInstance()) return this;
        if (other.hasToken()) {
          bitField0_ |= 0x00000001;
          token_ = other.token_;
          onChanged();
        }
        if (other.hasUin()) {
          setUin(other.getUin());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasToken()) {
          return false;
        }
        if (!hasUin()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.online.console.data.protobuf.java.AuthProtos.AuthRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.online.console.data.protobuf.java.AuthProtos.AuthRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object token_ = "";
      /**
       * <pre>
       * 用户 token
       * </pre>
       *
       * <code>required string token = 1;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 用户 token
       * </pre>
       *
       * <code>required string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户 token
       * </pre>
       *
       * <code>required string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户 token
       * </pre>
       *
       * <code>required string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户 token
       * </pre>
       *
       * <code>required string token = 1;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户 token
       * </pre>
       *
       * <code>required string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }

      private int uin_ ;
      /**
       * <pre>
       * 用户唯一识别码
       * </pre>
       *
       * <code>required int32 uin = 2;</code>
       */
      public boolean hasUin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 用户唯一识别码
       * </pre>
       *
       * <code>required int32 uin = 2;</code>
       */
      public int getUin() {
        return uin_;
      }
      /**
       * <pre>
       * 用户唯一识别码
       * </pre>
       *
       * <code>required int32 uin = 2;</code>
       */
      public Builder setUin(int value) {
        bitField0_ |= 0x00000002;
        uin_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户唯一识别码
       * </pre>
       *
       * <code>required int32 uin = 2;</code>
       */
      public Builder clearUin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        uin_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       * 发包时间戳
       * </pre>
       *
       * <code>required int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 发包时间戳
       * </pre>
       *
       * <code>required int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       * 发包时间戳
       * </pre>
       *
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发包时间戳
       * </pre>
       *
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.online.console.data.protobuf.proto.AuthRequest)
    }

    // @@protoc_insertion_point(class_scope:com.online.console.data.protobuf.proto.AuthRequest)
    private static final com.online.console.data.protobuf.java.AuthProtos.AuthRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.online.console.data.protobuf.java.AuthProtos.AuthRequest();
    }

    public static com.online.console.data.protobuf.java.AuthProtos.AuthRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AuthRequest>
        PARSER = new com.google.protobuf.AbstractParser<AuthRequest>() {
      @java.lang.Override
      public AuthRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.online.console.data.protobuf.java.AuthProtos.AuthRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.online.console.data.protobuf.proto.AuthResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 状态，使用枚举
     * </pre>
     *
     * <code>optional int32 status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <pre>
     * 状态，使用枚举
     * </pre>
     *
     * <code>optional int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <pre>
     * 错误码，统一定义的错误码
     * </pre>
     *
     * <code>optional int32 err_code = 2;</code>
     */
    boolean hasErrCode();
    /**
     * <pre>
     * 错误码，统一定义的错误码
     * </pre>
     *
     * <code>optional int32 err_code = 2;</code>
     */
    int getErrCode();

    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>optional string err_msg = 3;</code>
     */
    boolean hasErrMsg();
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>optional string err_msg = 3;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>optional string err_msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code com.online.console.data.protobuf.proto.AuthResponse}
   */
  public  static final class AuthResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.online.console.data.protobuf.proto.AuthResponse)
      AuthResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthResponse.newBuilder() to construct.
    private AuthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthResponse() {
      errMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errCode_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              errMsg_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.online.console.data.protobuf.java.AuthProtos.AuthResponse.class, com.online.console.data.protobuf.java.AuthProtos.AuthResponse.Builder.class);
    }

    /**
     * <pre>
     * 状态枚举
     * </pre>
     *
     * Protobuf enum {@code com.online.console.data.protobuf.proto.AuthResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0),
      /**
       * <code>ERR = -1;</code>
       */
      ERR(-1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>ERR = -1;</code>
       */
      public static final int ERR_VALUE = -1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return OK;
          case -1: return ERR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.online.console.data.protobuf.java.AuthProtos.AuthResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.online.console.data.protobuf.proto.AuthResponse.Status)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <pre>
     * 状态，使用枚举
     * </pre>
     *
     * <code>optional int32 status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 状态，使用枚举
     * </pre>
     *
     * <code>optional int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int ERR_CODE_FIELD_NUMBER = 2;
    private int errCode_;
    /**
     * <pre>
     * 错误码，统一定义的错误码
     * </pre>
     *
     * <code>optional int32 err_code = 2;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 错误码，统一定义的错误码
     * </pre>
     *
     * <code>optional int32 err_code = 2;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int ERR_MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errMsg_;
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>optional string err_msg = 3;</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>optional string err_msg = 3;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 错误描述
     * </pre>
     *
     * <code>optional string err_msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, errCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.online.console.data.protobuf.java.AuthProtos.AuthResponse)) {
        return super.equals(obj);
      }
      com.online.console.data.protobuf.java.AuthProtos.AuthResponse other = (com.online.console.data.protobuf.java.AuthProtos.AuthResponse) obj;

      boolean result = true;
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && (getStatus()
            == other.getStatus());
      }
      result = result && (hasErrCode() == other.hasErrCode());
      if (hasErrCode()) {
        result = result && (getErrCode()
            == other.getErrCode());
      }
      result = result && (hasErrMsg() == other.hasErrMsg());
      if (hasErrMsg()) {
        result = result && getErrMsg()
            .equals(other.getErrMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasErrMsg()) {
        hash = (37 * hash) + ERR_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.online.console.data.protobuf.java.AuthProtos.AuthResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.online.console.data.protobuf.proto.AuthResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.online.console.data.protobuf.proto.AuthResponse)
        com.online.console.data.protobuf.java.AuthProtos.AuthResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.online.console.data.protobuf.java.AuthProtos.AuthResponse.class, com.online.console.data.protobuf.java.AuthProtos.AuthResponse.Builder.class);
      }

      // Construct using com.online.console.data.protobuf.java.AuthProtos.AuthResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.online.console.data.protobuf.java.AuthProtos.internal_static_com_online_console_data_protobuf_proto_AuthResponse_descriptor;
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.AuthProtos.AuthResponse getDefaultInstanceForType() {
        return com.online.console.data.protobuf.java.AuthProtos.AuthResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.AuthProtos.AuthResponse build() {
        com.online.console.data.protobuf.java.AuthProtos.AuthResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.AuthProtos.AuthResponse buildPartial() {
        com.online.console.data.protobuf.java.AuthProtos.AuthResponse result = new com.online.console.data.protobuf.java.AuthProtos.AuthResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          result.errCode_ = errCode_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          result.errMsg_ = errMsg_;
          to_bitField0_ |= 0x00000004;
        } else {
          result.errMsg_ = "";
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.online.console.data.protobuf.java.AuthProtos.AuthResponse) {
          return mergeFrom((com.online.console.data.protobuf.java.AuthProtos.AuthResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.online.console.data.protobuf.java.AuthProtos.AuthResponse other) {
        if (other == com.online.console.data.protobuf.java.AuthProtos.AuthResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000004;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.online.console.data.protobuf.java.AuthProtos.AuthResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.online.console.data.protobuf.java.AuthProtos.AuthResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ ;
      /**
       * <pre>
       * 状态，使用枚举
       * </pre>
       *
       * <code>optional int32 status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 状态，使用枚举
       * </pre>
       *
       * <code>optional int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 状态，使用枚举
       * </pre>
       *
       * <code>optional int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态，使用枚举
       * </pre>
       *
       * <code>optional int32 status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <pre>
       * 错误码，统一定义的错误码
       * </pre>
       *
       * <code>optional int32 err_code = 2;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 错误码，统一定义的错误码
       * </pre>
       *
       * <code>optional int32 err_code = 2;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <pre>
       * 错误码，统一定义的错误码
       * </pre>
       *
       * <code>optional int32 err_code = 2;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000002;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码，统一定义的错误码
       * </pre>
       *
       * <code>optional int32 err_code = 2;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>optional string err_msg = 3;</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>optional string err_msg = 3;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>optional string err_msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>optional string err_msg = 3;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>optional string err_msg = 3;</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误描述
       * </pre>
       *
       * <code>optional string err_msg = 3;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.online.console.data.protobuf.proto.AuthResponse)
    }

    // @@protoc_insertion_point(class_scope:com.online.console.data.protobuf.proto.AuthResponse)
    private static final com.online.console.data.protobuf.java.AuthProtos.AuthResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.online.console.data.protobuf.java.AuthProtos.AuthResponse();
    }

    public static com.online.console.data.protobuf.java.AuthProtos.AuthResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AuthResponse>
        PARSER = new com.google.protobuf.AbstractParser<AuthResponse>() {
      @java.lang.Override
      public AuthResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.online.console.data.protobuf.java.AuthProtos.AuthResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_online_console_data_protobuf_proto_AuthRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_online_console_data_protobuf_proto_AuthRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_online_console_data_protobuf_proto_AuthResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_online_console_data_protobuf_proto_AuthResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;main/java/com/online/console/data/prot" +
      "obuf/proto/Auth.proto\022&com.online.consol" +
      "e.data.protobuf.proto\"<\n\013AuthRequest\022\r\n\005" +
      "token\030\001 \002(\t\022\013\n\003uin\030\002 \002(\005\022\021\n\ttimestamp\030\003 " +
      "\002(\003\"e\n\014AuthResponse\022\016\n\006status\030\001 \001(\005\022\020\n\010e" +
      "rr_code\030\002 \001(\005\022\017\n\007err_msg\030\003 \001(\t\"\"\n\006Status" +
      "\022\006\n\002OK\020\000\022\020\n\003ERR\020\377\377\377\377\377\377\377\377\377\001B3\n%com.online" +
      ".console.data.protobuf.javaB\nAuthProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_online_console_data_protobuf_proto_AuthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_online_console_data_protobuf_proto_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_online_console_data_protobuf_proto_AuthRequest_descriptor,
        new java.lang.String[] { "Token", "Uin", "Timestamp", });
    internal_static_com_online_console_data_protobuf_proto_AuthResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_online_console_data_protobuf_proto_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_online_console_data_protobuf_proto_AuthResponse_descriptor,
        new java.lang.String[] { "Status", "ErrCode", "ErrMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
