// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/java/com/online/console/data/protobuf/proto/Kickout.proto

package com.online.console.data.protobuf.java;

public final class KickoutProto {
  private KickoutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KickoutRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.online.console.data.protobuf.proto.KickoutRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 踢人原因
     * </pre>
     *
     * <code>required int32 reason = 1;</code>
     */
    boolean hasReason();
    /**
     * <pre>
     * 踢人原因
     * </pre>
     *
     * <code>required int32 reason = 1;</code>
     */
    int getReason();
  }
  /**
   * Protobuf type {@code com.online.console.data.protobuf.proto.KickoutRequest}
   */
  public  static final class KickoutRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.online.console.data.protobuf.proto.KickoutRequest)
      KickoutRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KickoutRequest.newBuilder() to construct.
    private KickoutRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KickoutRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KickoutRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              reason_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.online.console.data.protobuf.java.KickoutProto.KickoutRequest.class, com.online.console.data.protobuf.java.KickoutProto.KickoutRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code com.online.console.data.protobuf.proto.KickoutRequest.Reason}
     */
    public enum Reason
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 其他地方登陆
       * </pre>
       *
       * <code>OTHER_LOGIN = 0;</code>
       */
      OTHER_LOGIN(0),
      ;

      /**
       * <pre>
       * 其他地方登陆
       * </pre>
       *
       * <code>OTHER_LOGIN = 0;</code>
       */
      public static final int OTHER_LOGIN_VALUE = 0;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Reason valueOf(int value) {
        return forNumber(value);
      }

      public static Reason forNumber(int value) {
        switch (value) {
          case 0: return OTHER_LOGIN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Reason>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Reason> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Reason>() {
              public Reason findValueByNumber(int number) {
                return Reason.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.online.console.data.protobuf.java.KickoutProto.KickoutRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Reason[] VALUES = values();

      public static Reason valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Reason(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.online.console.data.protobuf.proto.KickoutRequest.Reason)
    }

    private int bitField0_;
    public static final int REASON_FIELD_NUMBER = 1;
    private int reason_;
    /**
     * <pre>
     * 踢人原因
     * </pre>
     *
     * <code>required int32 reason = 1;</code>
     */
    public boolean hasReason() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 踢人原因
     * </pre>
     *
     * <code>required int32 reason = 1;</code>
     */
    public int getReason() {
      return reason_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasReason()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, reason_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reason_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.online.console.data.protobuf.java.KickoutProto.KickoutRequest)) {
        return super.equals(obj);
      }
      com.online.console.data.protobuf.java.KickoutProto.KickoutRequest other = (com.online.console.data.protobuf.java.KickoutProto.KickoutRequest) obj;

      boolean result = true;
      result = result && (hasReason() == other.hasReason());
      if (hasReason()) {
        result = result && (getReason()
            == other.getReason());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasReason()) {
        hash = (37 * hash) + REASON_FIELD_NUMBER;
        hash = (53 * hash) + getReason();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.online.console.data.protobuf.java.KickoutProto.KickoutRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.online.console.data.protobuf.proto.KickoutRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.online.console.data.protobuf.proto.KickoutRequest)
        com.online.console.data.protobuf.java.KickoutProto.KickoutRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.online.console.data.protobuf.java.KickoutProto.KickoutRequest.class, com.online.console.data.protobuf.java.KickoutProto.KickoutRequest.Builder.class);
      }

      // Construct using com.online.console.data.protobuf.java.KickoutProto.KickoutRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        reason_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutRequest_descriptor;
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.KickoutProto.KickoutRequest getDefaultInstanceForType() {
        return com.online.console.data.protobuf.java.KickoutProto.KickoutRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.KickoutProto.KickoutRequest build() {
        com.online.console.data.protobuf.java.KickoutProto.KickoutRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.KickoutProto.KickoutRequest buildPartial() {
        com.online.console.data.protobuf.java.KickoutProto.KickoutRequest result = new com.online.console.data.protobuf.java.KickoutProto.KickoutRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          result.reason_ = reason_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.online.console.data.protobuf.java.KickoutProto.KickoutRequest) {
          return mergeFrom((com.online.console.data.protobuf.java.KickoutProto.KickoutRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.online.console.data.protobuf.java.KickoutProto.KickoutRequest other) {
        if (other == com.online.console.data.protobuf.java.KickoutProto.KickoutRequest.getDefaultInstance()) return this;
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasReason()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.online.console.data.protobuf.java.KickoutProto.KickoutRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.online.console.data.protobuf.java.KickoutProto.KickoutRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int reason_ ;
      /**
       * <pre>
       * 踢人原因
       * </pre>
       *
       * <code>required int32 reason = 1;</code>
       */
      public boolean hasReason() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 踢人原因
       * </pre>
       *
       * <code>required int32 reason = 1;</code>
       */
      public int getReason() {
        return reason_;
      }
      /**
       * <pre>
       * 踢人原因
       * </pre>
       *
       * <code>required int32 reason = 1;</code>
       */
      public Builder setReason(int value) {
        bitField0_ |= 0x00000001;
        reason_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 踢人原因
       * </pre>
       *
       * <code>required int32 reason = 1;</code>
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reason_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.online.console.data.protobuf.proto.KickoutRequest)
    }

    // @@protoc_insertion_point(class_scope:com.online.console.data.protobuf.proto.KickoutRequest)
    private static final com.online.console.data.protobuf.java.KickoutProto.KickoutRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.online.console.data.protobuf.java.KickoutProto.KickoutRequest();
    }

    public static com.online.console.data.protobuf.java.KickoutProto.KickoutRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<KickoutRequest>
        PARSER = new com.google.protobuf.AbstractParser<KickoutRequest>() {
      @java.lang.Override
      public KickoutRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KickoutRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KickoutRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KickoutRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.online.console.data.protobuf.java.KickoutProto.KickoutRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KickoutResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.online.console.data.protobuf.proto.KickoutResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * kickout 的响应包没有包体，client也可以不回响应包
   * </pre>
   *
   * Protobuf type {@code com.online.console.data.protobuf.proto.KickoutResponse}
   */
  public  static final class KickoutResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.online.console.data.protobuf.proto.KickoutResponse)
      KickoutResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KickoutResponse.newBuilder() to construct.
    private KickoutResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KickoutResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KickoutResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.online.console.data.protobuf.java.KickoutProto.KickoutResponse.class, com.online.console.data.protobuf.java.KickoutProto.KickoutResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.online.console.data.protobuf.java.KickoutProto.KickoutResponse)) {
        return super.equals(obj);
      }
      com.online.console.data.protobuf.java.KickoutProto.KickoutResponse other = (com.online.console.data.protobuf.java.KickoutProto.KickoutResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.online.console.data.protobuf.java.KickoutProto.KickoutResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * kickout 的响应包没有包体，client也可以不回响应包
     * </pre>
     *
     * Protobuf type {@code com.online.console.data.protobuf.proto.KickoutResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.online.console.data.protobuf.proto.KickoutResponse)
        com.online.console.data.protobuf.java.KickoutProto.KickoutResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.online.console.data.protobuf.java.KickoutProto.KickoutResponse.class, com.online.console.data.protobuf.java.KickoutProto.KickoutResponse.Builder.class);
      }

      // Construct using com.online.console.data.protobuf.java.KickoutProto.KickoutResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.online.console.data.protobuf.java.KickoutProto.internal_static_com_online_console_data_protobuf_proto_KickoutResponse_descriptor;
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.KickoutProto.KickoutResponse getDefaultInstanceForType() {
        return com.online.console.data.protobuf.java.KickoutProto.KickoutResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.KickoutProto.KickoutResponse build() {
        com.online.console.data.protobuf.java.KickoutProto.KickoutResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.online.console.data.protobuf.java.KickoutProto.KickoutResponse buildPartial() {
        com.online.console.data.protobuf.java.KickoutProto.KickoutResponse result = new com.online.console.data.protobuf.java.KickoutProto.KickoutResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.online.console.data.protobuf.java.KickoutProto.KickoutResponse) {
          return mergeFrom((com.online.console.data.protobuf.java.KickoutProto.KickoutResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.online.console.data.protobuf.java.KickoutProto.KickoutResponse other) {
        if (other == com.online.console.data.protobuf.java.KickoutProto.KickoutResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.online.console.data.protobuf.java.KickoutProto.KickoutResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.online.console.data.protobuf.java.KickoutProto.KickoutResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.online.console.data.protobuf.proto.KickoutResponse)
    }

    // @@protoc_insertion_point(class_scope:com.online.console.data.protobuf.proto.KickoutResponse)
    private static final com.online.console.data.protobuf.java.KickoutProto.KickoutResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.online.console.data.protobuf.java.KickoutProto.KickoutResponse();
    }

    public static com.online.console.data.protobuf.java.KickoutProto.KickoutResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<KickoutResponse>
        PARSER = new com.google.protobuf.AbstractParser<KickoutResponse>() {
      @java.lang.Override
      public KickoutResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KickoutResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KickoutResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KickoutResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.online.console.data.protobuf.java.KickoutProto.KickoutResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_online_console_data_protobuf_proto_KickoutRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_online_console_data_protobuf_proto_KickoutRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_online_console_data_protobuf_proto_KickoutResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_online_console_data_protobuf_proto_KickoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>main/java/com/online/console/data/prot" +
      "obuf/proto/Kickout.proto\022&com.online.con" +
      "sole.data.protobuf.proto\";\n\016KickoutReque" +
      "st\022\016\n\006reason\030\001 \002(\005\"\031\n\006Reason\022\017\n\013OTHER_LO" +
      "GIN\020\000\"\021\n\017KickoutResponseB5\n%com.online.c" +
      "onsole.data.protobuf.javaB\014KickoutProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_online_console_data_protobuf_proto_KickoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_online_console_data_protobuf_proto_KickoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_online_console_data_protobuf_proto_KickoutRequest_descriptor,
        new java.lang.String[] { "Reason", });
    internal_static_com_online_console_data_protobuf_proto_KickoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_online_console_data_protobuf_proto_KickoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_online_console_data_protobuf_proto_KickoutResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
